require 'test_helper'

class FamiliesControllerTest < ActionController::TestCase
  # This was generated by a scaffold and is not currently working. I don't know
  # why. Leaving it here commented in case it's an easy fix.

  # setup do
  #   @family = families(:johnson)
  # end

  # test "should get index" do
  #   get :index
  #   assert_response :success
  #   assert_not_nil assigns(:families)
  # end

  # test "should get new" do
  #   get :new
  #   assert_response :success
  # end

  # test "should create family" do
  #   assert_difference('Family.count') do
  #     post :create, family: { city: @family.city, name: @family.name, state: @family.state, street_address: @family.street_address, zip: @family.zip }
  #   end

  #   assert_redirected_to family_path(assigns(:family))
  # end

  # test "should show family" do
  #   get :show, id: @family.id
  #   assert_response :success
  # end

  # test "should get edit" do
  #   get :edit, id: @family.id
  #   assert_response :success
  # end

  # test "should update family" do
  #   patch :update, id: @family, family: { city: @family.city, name: @family.name, state: @family.state, street_address: @family.street_address, zip: @family.zip }
  #   assert_redirected_to family_path(assigns(:family))
  # end

  # test "should destroy family" do
  #   assert_difference('Family.count', -1) do
  #     delete :destroy, id: @family
  #   end

  #   assert_redirected_to families_path
  # end
end
